#%RAML 1.0 DataType
type: object
properties:
  film_id: integer
  title: string
  description?: string
  release_year?: integer
  language_id: integer
  original_language_id?: integer
  rental_duration: integer
  rental_rate: number
  length?: integer
  replacement_cost: number
  rating?: string
  special_features?: string[]
  last_update: datetime
